### ISSUE TITLE
Mac OS Sonoma / Liberica 17.0.9 - Can't start redis server

### ISSUE THREAD

**Issue by sethmreagan** [codemonstur/embedded-redis#17]
Was working until I upgraded to Sonoma. Seems to immediately execute processExited on the stdout stream even before it starts up.

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddedRedis': Invocation of init method failed; nested exception is java.lang.RuntimeException: Can't start redis server. Check logs for details. Redis process log: 
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:920)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:136)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:141)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:90)
	... 64 more
Caused by: java.lang.RuntimeException: Can't start redis server. Check logs for details. Redis process log: 
	at redis.embedded.AbstractRedisInstance.awaitRedisServerReady(AbstractRedisInstance.java:70)
	at redis.embedded.AbstractRedisInstance.start(AbstractRedisInstance.java:42)
	at redis.embedded.RedisServer.start(RedisServer.java:9)
	at redis.embedded.Redis$start$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
```

**Comment by codemonstur** [comment]
Looks like the default binary included in the jar is not compatible with this version of MacOS. The Redis people don't provide binaries so the one that is included was downloaded from a different source. There isn't anything I can do about this. For one, I don't have a mac. So I can't compile anything myself. And two, I don't have an alternate source for binaries. And even if I did how would I know this new binary is compatible with more versions of MacOS?

You can check if it is the binary by running it from the jar to see if it does indeed fail. If you are lucky it's something simple you can fix with a config setting.

If that doesn't work your best option is to compile your own binaries against whatever operating systems you need to support and provide them as alternatives in the builder.

**Comment by codemonstur** [comment]
I've added hank's binary in the gitrepo and updated the code with a new ExecutableProvider that can download a binary from a URI and run it. It may be useful to you.

**Comment by leandremucyo** [comment]
@sethmreagan I faced similar issue but I was using https://github.com/ozimov/embedded-redis using com.github.codemonstur:embedded-redis:1.3.0 is working with Sonoma 14.2.1

I noticed others using ozimov/embedded-redis faced similar issue https://stackoverflow.com/questions/77304264/cant-start-redis-server-exception-occurs-when-trying-to-run-spring-boot-on-my and solution was to use com.github.codemonstur:embedded-redis (this)

**Comment by fjosescarmona** [comment]
on mac you need to install one more dependency related to ssl, if i'm not wrong is libssl-dev.

In the class RedisInstance.java, the method start i modify this line:

throw new IOException("Failed to start Redis service", e);

to this:

throw new IOException("Failed to start Redis service", e.getCause());

so in that way you can get the error detail.

**Comment by codemonstur** [comment]
> throw new IOException("Failed to start Redis service", e.getCause());

Making this change would hide the exception being thrown. The existing code is the correct way to chain the exceptions together. If you want to see only the last on in the chain just keep calling getCause() until you have it.
