### ISSUE TITLE
Redis server is started but not detected by awaitServerReady (Windows + French JVM)

### ISSUE THREAD

**Issue by phycctv** [codemonstur/embedded-redis#22]
logs:
```
2023/12/04 18:04:31.020  [main] ERROR c.e.checkout.air.acceptance.RunMocks - Embedded Redis can't be started 
java.io.IOException: Failed to start Redis service
	at redis.embedded.RedisInstance.start(RedisInstance.java:56)
	at com.egencia.checkout.air.acceptance.RunMocks.startEmbeddedRedisServer(RunMocks.java:92)
	at com.egencia.checkout.air.acceptance.RunMocks.main(RunMocks.java:28)
Caused by: java.io.IOException: Ready pattern not found in log. Startup log: 
[21612] 04 Dec 18:04:30.982 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
[21612] 04 Dec 18:04:30.982 # Redis version=5.0.14.1, bits=64, commit=ec77f72d, modified=0, pid=21612, just started
[21612] 04 Dec 18:04:30.982 # Configuration loaded
[21612] 04 Dec 18:04:30.993 # Could not create server TCP listening socket 127.0.0.1:6380: bind: L�op�ration a r�ussi.
	at redis.embedded.RedisInstance.awaitServerReady(RedisInstance.java:63)
	at redis.embedded.RedisInstance.start(RedisInstance.java:46)
	... 2 common frames omitted
```
3 options : 

- Force JVM to English
- Start redis with Local.EN (not sure if it's possible)
- change SERVER_READY_PATTERN to fit more languages 

Thanks

**Comment by phycctv** [comment]
redis actually failed to start
