### ISSUE TITLE
Problem with windows path in executable property

### ISSUE THREAD

**Issue by FrodeBjerkholt** [codemonstur/embedded-redis#30]
When running embedded-redis in a Spring Boot application on the windows platform I see that the properties are reported as:
```properties
# Server
redis_version:5.0.14.1
redis_git_sha1:ec77f72d
redis_git_dirty:0
redis_build_id:5627b8177c9289c
redis_mode:standalone
os:Windows
arch_bits:64
multiplexing_api:WinSock_IOCP
atomicvar_api:pthread-mutex
process_id:19064
run_id:37a1ac07c23516033e32089140f8751938ce60b6
tcp_port:6379
uptime_in_seconds:5
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:14936499
executable:c:\users\testuser\appdata\local\temp\redis-3179602185899323378\redis-server-5.0.14.1-windows-amd64.exe
config_file:C:\Users\testuser\AppData\Local\Temp\embedded-redis-server_637915615375072325122685.conf
````

Spring Redis failes when parsing the executable property because it interprets the \u  in "c:\users" as an escaped unicode character:

```java
Caused by: java.lang.IllegalArgumentException: Malformed \uxxxx encoding.
	at java.base/java.util.Properties.loadConvert(Properties.java:663)
	at java.base/java.util.Properties.load0(Properties.java:457)
	at java.base/java.util.Properties.load(Properties.java:383)
	at org.springframework.data.redis.connection.convert.Converters.toProperties(Converters.java:111)
```

I not sure if this is bug in embedded-redis or that Spring Boot should adjust the reading code?

**Comment by codemonstur** [comment]
It's not clear to me what you are doing. Can you include some of your code so I can see how you are using the library?
