### ISSUE TITLE
Can't start redis server in Apple M1 chips

### ISSUE THREAD

**Issue by pinxiong** [codemonstur/embedded-redis#6]
## Environment
+ Operating System: Mac OS X
+ OS version: 10.16
+ Chip: Apple M1
+ Arch: x86_64
+ Java version: 11.0.9

## Problem

see [#7421](https://github.com/apache/dubbo/issues/7421)

## Suggestion

I think the best way to solve this problem is to upgrade the redis from `2.8.19` to `6.0.10` or `6.2 RC2` (see [#8062](https://github.com/redis/redis/issues/8062), [#8195](https://github.com/redis/redis/issues/8195)) 

We can get some more details from redis releases `6.0.10`

Bug fixes:

+ Fix setproctitle related crashes. ([#8150](https://github.com/redis/redis/issues/8150), [#8088](https://github.com/redis/redis/issues/8088))
Caused various crashes on startup, mainly on Apple M1 chips or under instrumentation

As @martin-g described, I believe this problem can be solved if I do as follows

1. downloads the Redis 6.x binary for Mac ARM64 M1
2. sets system property `embedded.redis.executable`, and the value is the absolute path of the Redis instance
3. use `ExecutableProvider.newSystemPropertyProvider()` to obtain `ExecutableProvider` for building Redis instance

However, I will update the code if I do like that.

In my opinion, there are two ways to solve it.

+ The one is that we can make customized Redis path first, and the call `ExecutableProvider#newEmbeddedRedis2_8_19Provider`
+ The other is that we can make the default redis version as `6.0.10`, because it's stable, unlikely to change
```java
static Map<OsArchitecture, String> newRedis2_8_19Map() {
        final Map<OsArchitecture, String> map = new HashMap<>();
        map.put(WINDOWS_x86, "/redis-server-2.8.19.exe");
        map.put(WINDOWS_x86_64, "/redis-server-2.8.19.exe");
        map.put(UNIX_x86, "/redis-server-2.8.19-32");
        map.put(UNIX_x86_64, "/redis-server-2.8.19");
        map.put(UNIX_AARCH64, "/redis-server-2.8.19-linux-aarch64");
        map.put(MAC_OS_X_x86, "/redis-server-2.8.19.app");
        map.put(MAC_OS_X_x86_64, "/redis-server-2.8.19.app");
        return map;
    }
```

In the long term, I think we should support these two options.

**Comment by codemonstur** [comment]
I would like to update Redis to a later version, 2.8.19 is quite old. Unfortunately I don't have a source for binaries. I can compile them myself but only for Windows and Linux and only for x86_64. I was able to also compile a version for arm using QEMU, (@martin-g helped a lot) but I have no mac available at all.

I documented some download locations here: https://github.com/codemonstur/embedded-redis/blob/master/src/docs/notes.md. But it's kinda sucky. The official site provides only source and the windows releases only go to 5.0.10. Preferably I'd want the same version of Redis for all platforms.

**Comment by codemonstur** [comment]
I created issue #7 for tracking updating redis. Maybe someone comes up with a solution.

**Comment by pinxiong** [comment]
> I would like to update Redis to a later version, 2.8.19 is quite old. Unfortunately I don't have a source for binaries. I can compile them myself but only for Windows and Linux and only for x86_64. I was able to also compile a version for arm using QEMU, (@martin-g helped a lot) but I have no mac available at all.
> 
> I documented some download locations here: https://github.com/codemonstur/embedded-redis/blob/master/src/docs/notes.md. But it's kinda sucky. The official site provides only source and the windows releases only go to 5.0.10. Preferably I'd want the same version of Redis for all platforms.

That's really a bad news! Can @martin-g give a help?

**Comment by codemonstur** [comment]
The other option is still available to you. ExecutableProvider is just an interface so you can add whatever logic you like. It shouldn't be hard to have a provider that checks if a variable is set and then fall back to the embedded redis if it is not.

**Comment by pinxiong** [comment]
I totally agree with you! But I think we can still provide some default implementation logic to give users more options, such as check if `embedded.redis.executable` set first, because nobody knows `ExecutableProvider.newSystemPropertyProvider()` exists and how to use it in the project.

**Comment by codemonstur** [comment]
I created issues #8, #9 and #10. I'll be implementing these as soon as I get around to it. Feel free to add ideas or comments. Heck, you can do them if you like :)

**Comment by martin-g** [comment]
>  because nobody knows `ExecutableProvider.newSystemPropertyProvider()` exists and how to use it in the project.

I know about it and it is obvious how to use it!
My apologies, @pinxiong, but it seems you just expect someone else to do your homework!
Please point me to your project where you have tried to implement support for Mac M1 and you have failed! If the commit dates are older than this comment then I will allocate time to debug and fix all issues for you!

**Comment by pinxiong** [comment]
> > because nobody knows `ExecutableProvider.newSystemPropertyProvider()` exists and how to use it in the project.
> 
> I know about it and it is obvious how to use it!
> My apologies, @pinxiong, but it seems you just expect someone else to do your homework!
> Please point me to your project where you have tried to implement support for Mac M1 and you have failed! If the commit dates are older than this comment then I will allocate time to debug and fix all issues for you!

Thanks for your help!

I'm trying to build [dubbo](https://github.com/apache/dubbo) project and learn it. However, some test cases cannot passed because all of them are related Redis which cannot support for Mac M1 chip.

Now, I disabled all of failed test cases, the [dubbo](https://github.com/apache/dubbo) project can work well, despite a slight imperfection.

You can see [#7421](https://github.com/apache/dubbo/issues/7421) to get the exception I have occurred.

**Comment by pinxiong** [comment]
> I created issues #8, #9 and #10. I'll be implementing these as soon as I get around to it. Feel free to add ideas or comments. Heck, you can do them if you like :)

Thank you! I'll do it if I have time, I'm building and debuging [dubbo](https://github.com/apache/dubbo) project first.

**Comment by martin-g** [comment]
> You can see [#7421](https://github.com/apache/dubbo/issues/7421) to get the exception I have occurred.

This is 29 days old. Since then we have improved embedded-redis to be able to run custom redis-server binary via custom ExecutableProvider. 

Now, to proceed you need to:

1) build latest Redis 6.x on your Mac M1
2) update RedisMetadataReportTest to use `ExecutableProvider.newSystemPropertyProvider()`
3) build Dubbo with: `mvn ... -Dembedded.redis.executable=/path/to/your/redis-server/built/at/1)`

**Comment by pinxiong** [comment]
> 3\. build Dubbo with: `mvn ... -Dembedded.redis.executable=/path/to/your/redis-server/built/at/1)`

I updated the test case `RedisMetadataReportTest`  as follows:

```java
@BeforeEach
public void constructor(TestInfo testInfo) throws IOException {
    int redisPort = NetUtils.getAvailablePort();
    // added
    System.setProperty("embedded.redis.executable","/Users/mypath/redis-server-2.8.19.app"); 
    String methodName = testInfo.getTestMethod().get().getName();
    if ("testAuthRedisMetadata".equals(methodName) || ("testWrongAuthRedisMetadata".equals(methodName))) {
        String password = "チェリー";
        // updated
        RedisServerBuilder builder = RedisServer.newRedisServer().executableProvider(ExecutableProvider.newSystemPropertyProvider()).port(redisPort).setting("requirepass " + password);
        if (SystemUtils.IS_OS_WINDOWS) {
            // set maxheap to fix Windows error 0x70 while starting redis
            builder.setting("maxheap 128mb");
        }
        redisServer = builder.build();
        registryUrl = URL.valueOf("redis://username:" + password + "@localhost:" + redisPort);
    } else {
        // updated
        RedisServerBuilder builder = RedisServer.newRedisServer().executableProvider(ExecutableProvider.newSystemPropertyProvider()).port(redisPort);
        if (SystemUtils.IS_OS_WINDOWS) {
            // set maxheap to fix Windows error 0x70 while starting redis
            builder.setting("maxheap 128mb");
        }
        redisServer = builder.build();
        registryUrl = URL.valueOf("redis://localhost:" + redisPort);
    }

    this.redisServer.start();
    redisMetadataReport = (RedisMetadataReport) new RedisMetadataReportFactory().createMetadataReport(registryUrl);
    URL asyncRegistryUrl = URL.valueOf("redis://localhost:" + redisPort + "?" + SYNC_REPORT_KEY + "=true");
    syncRedisMetadataReport = (RedisMetadataReport) new RedisMetadataReportFactory().createMetadataReport(registryUrl);
}
```

and then run the test cases, an exception occurred

```java
log4j:WARN No appenders could be found for logger (org.apache.dubbo.common.logger.LoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

java.io.IOException: Failed to start Redis service

	at redis.embedded.RedisInstance.start(RedisInstance.java:40)
	at org.apache.dubbo.metadata.store.redis.RedisMetadataReportTest.constructor(RedisMetadataReportTest.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptLifecycleMethod(TimeoutExtension.java:126)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptBeforeEachMethod(TimeoutExtension.java:76)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeMethodInExtensionContext(ClassBasedTestDescriptor.java:490)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$synthesizeBeforeEachMethodAdapter$19(ClassBasedTestDescriptor.java:475)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachMethods$2(TestMethodTestDescriptor.java:167)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeMethodsOrCallbacksUntilExceptionOccurs$5(TestMethodTestDescriptor.java:195)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:195)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachMethods(TestMethodTestDescriptor.java:164)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:127)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: java.io.IOException: Cannot run program "/Users/mypath/redis-server-2.8.19.app" (in directory "/Users/mypath"): error=13, Permission denied
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at redis.embedded.RedisInstance.start(RedisInstance.java:33)
	... 70 more
Caused by: java.io.IOException: error=13, Permission denied
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
```

**Comment by martin-g** [comment]
`Caused by: java.io.IOException: error=13, Permission denied` - Does `/Users/mypath/redis-server-2.8.19.app` have read and exec permissions ?

What is the output of `$ ls -la /Users/mypath/redis-server-2.8.19.app` ?

Why is it named 2.8.19 ? Did you build 2.8.19 on your Mac M1 ? You need to use latest 6.x

**Comment by pinxiong** [comment]
I don't know where I can download the Redis 6.x binary with *.app, I just have `redis-6.0.10.tar.gz` file, but I don't know how to build it to `redis-6.0.10.app` file

**Comment by martin-g** [comment]
You need to build from sources locally.
Almost every Open Source project releases only source code now. Only Operating Systems provide binary packages.
So try with `brew install redis` (or something similar) or build it locally with `make`. You need to ask Redis community to help you for this. If Redis itself cannot be built on Mac M1 then `embedded-redis` cannot help you.

**Comment by pinxiong** [comment]
Thanks for your proposal, I'll have a try.

**Comment by kingabotoslynx** [comment]
@pinxiong Hello, I am facing the same issue with the embedded-redis library on M1. Could you please tell me if this story has a happy end? :"> It is worth trying to make an executable redis 6 on chip M1? It is going to work? Thanks

**Comment by codemonstur** [comment]
@pinxiong I pushed a new version of the lib with a newer version of Redis. Can you check if it works for you?

**Comment by justin-tay** [comment]
Not the TS but I just tried this with `1.0.0` on a M1 and it seems to get the appropriate binary and work. I had to install openssl 3 though.

`brew install openssl@3`
